{% set name = "binpickle" %}
{% set version = "0.3.4" %}
package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13a35953d7f3470d571a97a904cbd42875b9a2a69a7181bf9a6e034d415426ee

build:
  number: 0
  # Binpickle is only tested on Python 3.6 and later
  # Dependencies are missing on pypy, and pickle5 is only on x86-64
  skip: true  # [py<36 or python_impl == 'pypy' or (py<38 and not x86_64)]
  script: {{ PYTHON }} -m pip install --no-deps .

requirements:
  build:
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
  host:
    - python
    - pip
    - flit-core >=2
  run:
    - python
    - python-blosc
    - msgpack-python >=1.0
    - pickle5  # [py<38]

test:
  requires:
    - pytest
    - hypothesis
    - pandas >= 1.0
    - numpy >= 1.17
    # numcodecs is only packaged for x86-64 - run without those tests on other platformss
    - numcodecs  # [x86_64]
  files:
    - conftest.py
  source_files:
    - tests
    - tests/*.py
  imports:
    - binpickle
    - binpickle.codecs.blosc
  commands:
    - python -m pytest tests

about:
  home: https://binpickle.lenskit.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Efficient binary storage of ML models
  description: |
    The binpickle module uses Pickle Protocol 5 to enable efficient serialization of
    Scientific Python models, such as those learned by scikit-learn, to disk in with
    their large arrays either compressed (optionall with Blosc) or configured for
    memory-mapped use to support shared memory multiprocessing.
  dev_url: https://github.com/lenskit/binpickle

extra:
  recipe-maintainers:
    - mdekstrand
