{% set name = "binpickle" %}
{% set version = "0.3.2" %}
package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fbd019e2160d279a41e3d5f9e9ea038e0c361fb6f5eecea8373666cf2865a4d1

build:
  number: 0
  # Binpickle is only tested on Python 3.6 and later.
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install --no-deps .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-blosc
    - msgpack-python >=1.0
    - pickle5  # [py<38]

test:
  imports:
    - binpickle
    - binpickle.codecs.blosc

about:
  home: https://binpickle.lenskit.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Efficient binary storage of ML models
  description: |
    The binpickle module uses Pickle Protocol 5 to enable efficient serialization of
    Scientific Python models, such as those learned by scikit-learn, to disk in with
    their large arrays either compressed (optionall with Blosc) or configured for
    memory-mapped use to support shared memory multiprocessing.
  dev_url: https://github.com/lenskit/binpickle

extra:
  recipe-maintainers:
    - mdekstrand
